### ISSUE TITLE
silkscreen values

### ISSUE THREAD

**Issue by KeLaiFu** [8bitPig/Mult#1]
a few of the values on the silkscreen are impossible to read on the PCB, I managed to fill the gaps looking at the gerber in a viewer, but on the actual PCB some numbers are lost under pads.

**Comment by 8bitPig** [comment]
yes, that is possible. 
I won't go for a revision because I think it is good enough. ^^
I'd recommend y'all to simply order the pcb assembled at jlcpcb. Then, you won't have the need to read the silkscreen. The whole design is dont to be SMD preassembled by JLC in stock components.
